### ISSUE TITLE
Official App?

### ISSUE THREAD

**Issue by sonic65101** [nyqst/radiohyrule-ana#12]
Does this have any relation to the official app (package name com.radiohyrule.caa) that vanished off the Google Play Store? I was able to transfer that app to my new phone from an old phone, but I'm concerned about it being outdated. Sorry for bothering you.

**Comment by awwright** [comment]
@sonic65101 This would be that app! `ana` is the name of the development version for various historical reasons. We've been bringing it up-to-date and I'll be working on publishing it in the coming week. Sorry for the inconvenience.
