### ISSUE TITLE
Notifications shouldn't vibrate phone

### ISSUE THREAD

**Issue by awwright** [nyqst/radiohyrule-ana#15]
@rocketgarden It seems somewhere in the last batch of updates, that starting the stream, loading metadata, and changing metadata causes a vibrate event when the notification changes.  This didn't happen release v0.0.8. Is this necessary?

**Comment by rocketgarden** [comment]
oh that is interesting and weird. android notification stuff has changed a bit since then so we're probably tripping over a change in the api.
It should definitely be possible to suppress

**Comment by awwright** [comment]
The solution here is s/IMPORTANCE_DEFAULT/IMPORTANCE_LOW/, and then uninstalling and re-installing the app, because apparently Android caches this setting? Ugh
